"""Create api_key table and add one-to-many-to-one relationship between users and brokers table

Revision ID: 064ace3fac5e
Revises: de7c9cb67b58
Create Date: 2026-01-22 14:59:00.836862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '064ace3fac5e'
down_revision: Union[str, Sequence[str], None] = 'de7c9cb67b58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('private_key', sa.String(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('brokers_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brokers_name'], ['brokers.name'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'brokers_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    # ### end Alembic commands ###
