"""Add portfolio_cash table with one-to-one-to-many relation between users, portfolio_cash and brokers

Revision ID: 8002bc49b99d
Revises: 064ace3fac5e
Create Date: 2026-02-03 16:16:02.218770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8002bc49b99d'
down_revision: Union[str, Sequence[str], None] = '064ace3fac5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_cash',
    sa.Column('current_value', sa.Float(), nullable=False),
    sa.Column('realised_profit_loss', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('unrealised_profit_loss', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('brokers_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['brokers_name'], ['brokers.name'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('users_id', 'brokers_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_cash')
    # ### end Alembic commands ###
